### ISSUE TITLE
A value can lose its type when there is cache hit

### ISSUE THREAD

**Issue by enzzc** [alexk307/redis_cache#3]
Cached values seem to be always retrieved and returned with type `str`. This can be a problem when a function is expected to return an `int` for example.

 ```python
>>> mytest.my_method(2,3,2) # cache miss
512
>>> mytest.my_method(2,3,2) # cache hit
'512'
```

What would be the best way to force a certain return type?

**Comment by alexk307** [comment]
Good catch!

I believe I fixed this last night by using the `pickle` module. Instead of converting everything to a string I'm pickling the object and un-pickling it when we load back from Redis. I would like to stay away from specifying a type to store since that to me seems less 'pythonic' FWIW.

I'm not sure if there are any limitations to using `pickle` but it seems to work with most objects/types.

**Comment by enzzc** [comment]
Yes, specifying a type would not be very pythonic... I've just pulled the changes, the pickle solution seems to work perfectly!

**Comment by alexk307** [comment]
Great! Let me know if you have any other issues :)
