### ISSUE TITLE
Change behavior of cache such that overriding the __str__ is no longer needed

### ISSUE THREAD

**Issue by alexk307** [alexk307/redis_cache#5]
As the note says in the README it is necessary to override the calling object's __str__ method as well as any objects passed into the function as parameters. This doesn't seem maintainable. We will have to create a way to do this behind the implicitly.

**Comment by c-w** [comment]
I came across this issue doing a Hacktoberfest search and it looked interesting, so I started looking into this... it seemed simple at first, but quickly became somewhat non-obvious.

My first idea was to just use `arg.__class__.__name__` to provide a default `__str__` when formatting cache keys for custom classes. This works well, but doesn't take into consideration classes that have methods whose return values vary by the class state. Example:

```python
class Counter(object):
  def __init__(self):
    self._count = 0

  def increment(self):
    self._count += 1

  @cache
  def current_count(self):
    return self._count
```

So that means that we need a way to represent the instance's state in the `__str__`, like some of the tests are already doing. We can use the `vars` builtin and recursion for that.

**Comment by c-w** [comment]
Let me know if you find #7 useful. It should remove the need for the custom `__str__` method in all common scenarios. It is also 100% backwards compatible: if an object defines a custom `__str__` method, we'll just use that.

**Comment by alexk307** [comment]
Good point, I didn't think of that! Looks good man, I just had a few comments.

**Comment by c-w** [comment]
@alexk307 Addressed the comments and updated the pull request.
